/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// Properties/Run y seleccionamos la clase que se va a ejecutar primero
package Principal;

/**
 *
 * @author Sáfico
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
  // private final String nomEmpresa2;
    public Principal() {
        initComponents();
        
        
       //this.nomEmpresa2 = LogIn.g;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInicio = new javax.swing.JPanel();
        botonVentas = new javax.swing.JButton();
        botonRecursos = new javax.swing.JButton();
        txtRecursos = new javax.swing.JLabel();
        txtVentas = new javax.swing.JLabel();
        nomEmpresa = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        txtPedido = new javax.swing.JLabel();
        txtTareas = new javax.swing.JLabel();
        botonPedido = new javax.swing.JButton();
        botonTareas = new javax.swing.JButton();
        botonPlantas = new javax.swing.JButton();
        jPlantas = new javax.swing.JLabel();
        jVentas = new javax.swing.JPanel();
        jPedidos = new javax.swing.JPanel();
        jRecursos = new javax.swing.JPanel();
        jTareas = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Resources/ventas.jpg"))); // NOI18N
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });

        botonRecursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Resources/invernadero.jpg"))); // NOI18N
        botonRecursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRecursosMouseClicked(evt);
            }
        });
        botonRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecursosActionPerformed(evt);
            }
        });

        txtRecursos.setText("Gestión de recursos");

        txtVentas.setText("Ventas");

        nomEmpresa.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        nomEmpresa.setText("Nombre de la empresa");

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        txtPedido.setText("pedido");

        txtTareas.setText("tareas");

        botonPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Resources/pedidos3.jpg"))); // NOI18N

        botonTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Resources/tareas.jpeg"))); // NOI18N
        botonTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTareasActionPerformed(evt);
            }
        });

        botonPlantas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Resources/planta.jpg"))); // NOI18N

        jPlantas.setText("Plantas");

        javax.swing.GroupLayout jInicioLayout = new javax.swing.GroupLayout(jInicio);
        jInicio.setLayout(jInicioLayout);
        jInicioLayout.setHorizontalGroup(
            jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(botonTareas)
                .addGap(152, 152, 152)
                .addComponent(botonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(botonRecursos)
                .addGap(174, 174, 174))
            .addGroup(jInicioLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInicioLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(nomEmpresa)
                        .addContainerGap())
                    .addGroup(jInicioLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(txtTareas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRecursos)
                        .addGap(299, 299, 299))
                    .addGroup(jInicioLayout.createSequentialGroup()
                        .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInicioLayout.createSequentialGroup()
                                .addComponent(botonPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jInicioLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(txtPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPlantas)
                                .addGap(260, 260, 260)))
                        .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                                .addComponent(botonVentas)
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                                .addComponent(txtVentas)
                                .addGap(220, 220, 220))))))
        );
        jInicioLayout.setVerticalGroup(
            jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioLayout.createSequentialGroup()
                .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInicioLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonRecursos)
                            .addComponent(botonTareas))
                        .addGap(18, 18, 18)
                        .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecursos)
                            .addComponent(txtTareas)))
                    .addGroup(jInicioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(nomEmpresa)
                        .addGap(116, 116, 116)
                        .addComponent(botonSalir)))
                .addGap(47, 47, 47)
                .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPlantas)
                        .addComponent(txtVentas))
                    .addComponent(txtPedido))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        botonTareas.getAccessibleContext().setAccessibleName("botonTareas");

        jTabbedPane1.addTab("Inicio", jInicio);

        javax.swing.GroupLayout jVentasLayout = new javax.swing.GroupLayout(jVentas);
        jVentas.setLayout(jVentasLayout);
        jVentasLayout.setHorizontalGroup(
            jVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jVentasLayout.setVerticalGroup(
            jVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ventas", jVentas);

        javax.swing.GroupLayout jPedidosLayout = new javax.swing.GroupLayout(jPedidos);
        jPedidos.setLayout(jPedidosLayout);
        jPedidosLayout.setHorizontalGroup(
            jPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jPedidosLayout.setVerticalGroup(
            jPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pedidos", jPedidos);

        javax.swing.GroupLayout jRecursosLayout = new javax.swing.GroupLayout(jRecursos);
        jRecursos.setLayout(jRecursosLayout);
        jRecursosLayout.setHorizontalGroup(
            jRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jRecursosLayout.setVerticalGroup(
            jRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gestión de recursos", jRecursos);

        javax.swing.GroupLayout jTareasLayout = new javax.swing.GroupLayout(jTareas);
        jTareas.setLayout(jTareasLayout);
        jTareasLayout.setHorizontalGroup(
            jTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jTareasLayout.setVerticalGroup(
            jTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tareas", jTareas);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVentasActionPerformed

    private void botonRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRecursosActionPerformed

    private void botonRecursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRecursosMouseClicked
       
        
    }//GEN-LAST:event_botonRecursosMouseClicked

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        
       dispose(); //Cerramos la ventana
    }//GEN-LAST:event_botonSalirMouseClicked

    private void botonTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTareasActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPedido;
    private javax.swing.JButton botonPlantas;
    private javax.swing.JButton botonRecursos;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTareas;
    private javax.swing.JButton botonVentas;
    private javax.swing.JPanel jInicio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPedidos;
    private javax.swing.JLabel jPlantas;
    private javax.swing.JPanel jRecursos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jTareas;
    private javax.swing.JPanel jVentas;
    private javax.swing.JLabel nomEmpresa;
    private javax.swing.JLabel txtPedido;
    private javax.swing.JLabel txtRecursos;
    private javax.swing.JLabel txtTareas;
    private javax.swing.JLabel txtVentas;
    // End of variables declaration//GEN-END:variables
}
